// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'mainwindow-copy-reader'
  | 'mainwindow-copy-selected'
  | 'menu-copy-reader'
  | 'menu-copy-reader-shortcut'
  | 'menu-copy-selected'
  | 'notify-copy-failed'
  | 'pref-compatibility-note'
  | 'pref-custom-types'
  | 'pref-custom-types-help'
  | 'pref-help'
  | 'pref-multi-attachment-mode'
  | 'pref-multi-attachment-mode-all'
  | 'pref-multi-attachment-mode-primary'
  | 'pref-reader-ctrl-c-mode'
  | 'pref-reader-ctrl-c-mode-always'
  | 'pref-reader-ctrl-c-mode-never'
  | 'pref-reader-ctrl-c-mode-smart'
  | 'pref-section-compatibility'
  | 'pref-section-copy'
  | 'pref-section-types'
  | 'pref-title'
  | 'pref-type-epub'
  | 'pref-type-mobi'
  | 'pref-type-pdf'
  | 'pref-type-presets'
  | 'pref-type-txt'
  | 'pref-type-validation'
  | 'prefs-title';
