// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'mainwindow-copy-reader'
  | 'mainwindow-copy-selected'
  | 'menu-copy-reader'
  | 'menu-copy-reader-shortcut'
  | 'menu-copy-selected'
  | 'notify-copy-failed'
  | 'pref-allow-path-fallback'
  | 'pref-compatibility-note'
  | 'pref-help'
  | 'pref-multi-pdf-mode'
  | 'pref-multi-pdf-mode-all'
  | 'pref-multi-pdf-mode-primary'
  | 'pref-reader-ctrl-c-mode'
  | 'pref-reader-ctrl-c-mode-always'
  | 'pref-reader-ctrl-c-mode-never'
  | 'pref-reader-ctrl-c-mode-smart'
  | 'pref-title'
  | 'prefs-title';
