// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "multiAttachmentMode": string;
      "libraryShortcut": string;
      "readerShortcut": string;
      "showMainToolbarButton": boolean;
      "showReaderToolbarButton": boolean;
      "enabledAttachmentTypes": string;
      "customAttachmentTypes": string;
      "showContextMenuEntry": boolean;
      "autoTaggingEnabled": boolean;
      "aiProvider": string;
      "aiApiEndpoint": string;
      "aiApiKeyDeepseek": string;
      "aiApiKeyOpenrouter": string;
      "aiApiKeyOllama": string;
      "aiApiKeyLmstudio": string;
      "aiApiKeyCustom": string;
      "aiEndpointOllama": string;
      "aiEndpointLmstudio": string;
      "aiModel": string;
      "aiLastModelOllama": string;
      "aiLastModelLmstudio": string;
      "aiLastModelCustom": string;
      "aiPrompt": string;
      "stripConnectorTags": boolean;
      "autoTagOnAdd": boolean;
    };
  }
}
