// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "multiAttachmentMode": string;
      "readerCtrlCMode": string;
      "libraryShortcut": string;
      "readerShortcut": string;
      "enabledAttachmentTypes": string;
      "customAttachmentTypes": string;
    };
  }
}
